version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:8080
    image: front-game-of-life:v3.0
    ports:
      - "80:80"